#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw($RealBin);

my @args = map {"\"$_\""} @ARGV;#hack for species argument that may contain spaces
system("java -jar $RealBin/dist/CodingToGenomic.jar @args");
